### ISSUE TITLE
Doesn't appear to work for Sass?

### ISSUE THREAD

**Issue by dustinhorton** [alampros/gatsby-plugin-resolve-src#1]
First plugin I install for Gatsby projects—thanks for the work.

Any Idea why this doesn't work for Sass?

I have a directory structure like:

```
src/
├── components/
├── layouts/
├── pages/
├── styles/
│   ├── app.scss
│   └── variables.scss
```

I still have to do imports like:

```scss
@import 'src/styles/variables';
```

…when it seems I should be able to do:

```scss
@import 'styles/variables';
```

Yet if I change your plugin to:

```js
exports.modifyWebpackConfig = ({ config, _stage }) => {
  return config.merge({
    resolve: {
      root: [
        path.resolve(config._config.context, 'src'),
        path.resolve(config._config.context, 'src/styles'),
      ]
    },
  })
}
```

I can write the above import like:

```scss
@import 'variables';
```

**Comment by alampros** [comment]
I think you might need to use a tilde (`~`) to have webpack resolve the import instead of libsass. Can you try this?

```scss
@import '~styles/variables';
```

If that doesn't work, you might have to modify the `include-path` option of `node-sass` to include the `src` dir.

**Comment by dustinhorton** [comment]
Oh interesting. That's actually what I'd be doing thus far, but erroneously thought that was working because I'd added this to `gatsby-node.js`:

```js
exports.modifyWebpackConfig = ({ config, _stage }) => {
  return config.merge({
    resolve: {
      alias: {
        styles: path.resolve(config._config.context, 'src/styles'),
      },
    },
  })
}
```

Just removed that and `~` still works as I'd been using it, and as you described above.

I'll look into `include-path` (`~` works, just curious and would make some code reuse a lot easier in my particular situation).

**Comment by dustinhorton** [comment]
Thanks for looking into this. Unfortunately for my setup, I don't believe anything has changed. I'm assuming it's because I'm using [gatsby-plugin-postcss-sass](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-postcss-sass)?

I made a repro @ https://github.com/dustinhorton/gatsby-plugin-resolve-src-issue if you want to check it out. Relevant lines:
* https://github.com/dustinhorton/gatsby-plugin-resolve-src-issue/blob/master/src/styles/app.scss#L1-L3
* https://github.com/dustinhorton/gatsby-plugin-resolve-src-issue/blob/master/src/components/Header/Header.module.scss#L1-L3

**Comment by alampros** [comment]
No problem - sorry it didn't help your situation!

I'm pretty sure you're right about postcss being the issue. I think you'll have to modify the resolvers yourself for the `postcss-import` plugin.

Another option might be to submit a gatsby ticket to have the `gatsby-plugin-postcss-sass` package add the `/src` directory to it's paths option by default.
