### ISSUE TITLE
Command+Click into component no longer works in VS Code with gatsby-plugin-resolve-src

### ISSUE THREAD

**Issue by ghost** [alampros/gatsby-plugin-resolve-src#10]
**Previous Behavior:**
`import Article from "../pages/Article"`
[Cmd+Click will bring you to the Article component]

**Behavior w/ gatsby-plugin-resolve-src:**
`import Article from "pages/Article"` (with gatsby-plugin-resolve-src)
[Cmd+Click does not bring you to the Article component]

Are there any changes I can make to my Workspace settings that will enable this behavior with gatsby-plugin-resolve-src? If so, it might be good to include that in the docs or FAQ.

Thank you! Love the plugin.

**Comment by alampros** [comment]
I believe this has to do with your typescript configuration. Take a look at [this solution](https://github.com/alampros/gatsby-plugin-resolve-src/issues/9#issuecomment-503559949) and reopen if that doesn't do the trick for you.
