### ISSUE TITLE
Is it Possible to Use This Library With a NODE_PATH of "."?

### ISSUE THREAD

**Issue by machineghost** [alampros/gatsby-plugin-resolve-src#13]
I'm trying to convert an existing site to Gatsby, and previously I had used:

    {
      "compilerOptions": {
        "baseUrl": "./",

To have imports like:

    import foo form 'src/foo';

Is that possible with this library?  When I try to do so I get "Can't resolve" errors.

**Comment by machineghost** [comment]
For anyone who finds this, it seems the answer is "No, but ..." 

It turns out there's a _separate_ plug-in called `gatsby-plugin-root-import` which does what I was looking for.  Now why does Gatsby require two separate plug-in libraries to set one single Webpack setting (or maybe two?)

That I could not tell you ... and that's why I'll leave this ticket open, with a new goal: merge this plugin with `gatsby-plugin-root-import` :)

**Comment by alampros** [comment]
Yes, you can just specify the `srcPath` yourself using something like:
```js
{
  resolve: 'gatsby-plugin-resolve-src',
  options: {
    srcPath: path.resolve(__dirname),
  },
},
```
