### ISSUE TITLE
Any way to make this work with CSS?

### ISSUE THREAD

**Issue by coreyward** [alampros/gatsby-plugin-resolve-src#2]
While this works great in JS, it doesn't seem to impact the `postcss-import` loader so CSS files still only work as relative paths (or absolute to your system root). Making matters worse, it's nearly impossible to find relevant issues where someone doesn't link to this plugin as the answer to this problem.  😔 

For clarity, I want to do this in my CSS and I'm only Gatsby's included PostCSS support (no Sass): 

    @import 'styles/foo'

…and have it work, regardless of whether the current file is at `src/styles/bar.css` or `src/styles/shared/bar.css`.

I've only recently jumped into the deep end with webpack, postcss, and Gatsby, so it could just be that I've missed something. 🤞

**Comment by alampros** [comment]
It looks like you should be able to get this to work by passing your styles dir to the [path](https://github.com/postcss/postcss-import#path) option of `postcss-import`.

How are you adding `postcss` to your project?

**Comment by coreyward** [comment]
As I mentioned I'm only using the Gatsby included PostCSS, so however it loads it is how I'm adding it. Literally `postcss` is a dependency of Gatsby and I do nothing else to get it working. 

That being the case, I don't know how to augment the configuration passed to `postcss-import`. I searched and tried to find configuration docs, but Gatsby seems like a wild-west.

**Comment by alampros** [comment]
Wow. I had no idea that was built-in. Nice!

I'll look into it. We should be able to do something similar to what I just did for `sass-loader` in `v1.1.0`.

**Comment by alampros** [comment]
Closing this as it is not related to this plugin.
