### ISSUE TITLE
FYI: Broken in node 8.11.1 LTS

### ISSUE THREAD

**Issue by VinSpee** [alampros/gatsby-plugin-resolve-src#3]
Hi! I was using this package (I love it and use it in all of my gatsby projects) in my project and the latest update broke because you introduced the [spread operator on an object](https://github.com/alampros/gatsby-plugin-resolve-src/blob/master/gatsby-node.js#L21). That means it is only compatible with node >= 9, which broke my build. 

I think it would be worthwhile to use `Object.assign()` instead for something like this.

LMK if you'd like me to PR.

**Comment by alampros** [comment]
🤦‍♂️  doh!

I'm using node@8.11.0 and it's working just fine, but that might because it's inheriting the babel setup from my project. I'll push a fix for this asap. Sorry!

**Comment by VinSpee** [comment]
no prob! I am very used to Object spread as well haha

**Comment by alampros** [comment]
Try v1.1.3 - should be v8.x compatible now

**Comment by VinSpee** [comment]
thanks!
