### ISSUE TITLE
Broken with Gatsby v2

### ISSUE THREAD

**Issue by etnbrd** [alampros/gatsby-plugin-resolve-src#4]
I think this module will break with Gatsby v2, as the api hook changed from `modifyWebpackConfig` to `onCreateWebpackConfig`.
It seems to be documented here : https://next.gatsbyjs.org/docs/add-custom-webpack-config/

**Comment by RIP21** [comment]
Also, I may assume that the fact that Webpack 4 is in v2 will require a little adjustment of the code too.

**Comment by RIP21** [comment]
For anyone who appeared to come here to make `/src` resolve working again this may help you:
```
exports.onCreateWebpackConfig = ({ stage, actions }) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, "src"), "node_modules"],
    },
  })
}
```
Just add this to the `gatsby-node.js`

If you need SAAS/SCSS functionality aswell, you will need to go a bit deeper, so check out the link that @etnbrd provided for more info.

**Comment by noudadrichem** [comment]
This module did break in v2. Thanks @RIP21 for providing this snippet, only problem is that for some reason es6 syntax for importing/exporting also breaks.

**Comment by alampros** [comment]
Thanks @RIP21 – I'll publish a `@next` tag with this change soon!

**Comment by alampros** [comment]
[v2.0.0-beta.1](https://www.npmjs.com/package/gatsby-plugin-resolve-src/v/2.0.0-beta.1) published to tag `@next`.
