### ISSUE TITLE
Doesn't work in browser

### ISSUE THREAD

**Issue by luskin** [alampros/gatsby-plugin-resolve-src#6]
This plugin works great for local development, however when deploying to server we receive the following error:

```
error Generating JavaScript bundles failed
       
       
         Error: ./src/pages/404.js
         Module not found: Error: Can't resolve 'Components/Layout' in '/tmp/build_6893  5b81aedae3c01855b42686ecdf9d/src/pages'
         resolve 'Components/Layout' in '/tmp/build_68935b81aedae3c01855b42686ecdf9d/sr  c/pages'
           Parsed request is a module
           using description file: /tmp/build_68935b81aedae3c01855b42686ecdf9d/package.  json (relative path: ./src/pages)
             Field 'browser' doesn't contain a valid alias configuration
             resolve as module

.....etc
```

Are there any specific settings that need to be put in `gatsby-browser.js` to make this work when building in our server?

Thanks!

**Comment by alampros** [comment]
This plugin doesn't touch the `gatsby-browser.js` api at all. I'd have to see more of your project structure to understand what's going on.

Are you able to share any of your project's structure (maybe other plugins in use also)?

(Sorry for the delayed response!)
