### ISSUE TITLE
Not compatible with Gatsby v2.

### ISSUE THREAD

**Issue by wouterlanduydt** [alampros/gatsby-plugin-resolve-src#7]
When migrating to Gatsby v2 (following [this](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/) migration guide), Gatsby throws an error:

```
Your plugins must export known APIs from their gatsby-node.js.
The following exports aren't APIs. Perhaps you made a typo or your plugin is outdated?

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby Node APIs

- The plugin "gatsby-plugin-resolve-src@1.1.4" is exporting a variable named "modifyWebpackConfig" which isn't an API.
```

**Comment by alampros** [comment]
The next branch should work for v2. Sorry - I haven't gotten around to promoting it to master yet.

You can install it with `yarn add gatsby-plugin-resolve-src@next`.
