### ISSUE TITLE
Publish support for Gatsby v2

### ISSUE THREAD

**Issue by AlanFoster** [alampros/gatsby-plugin-resolve-src#8]
Hey, it'd be great to publish the latest stable release of gatsby-plugin-resolve-src for anyone wanting to use this module with Gatsby v2 :+1:

**Comment by john-d-pelingo** [comment]
> Hey, it'd be great to publish the latest stable release of gatsby-plugin-resolve-src for anyone wanting to use this module with Gatsby v2 👍

@AlanFoster There's an example at the official docs https://www.gatsbyjs.org/docs/add-custom-webpack-config/#absolute-imports. It covered my use case perfectly. Hope it does for you as well.
