### ISSUE TITLE
VS Code "Jump to definition" does not work

### ISSUE THREAD

**Issue by antoinerousseau** [alampros/gatsby-plugin-resolve-src#9]
Any way we can make this work again? (clicking an import to go to the definition file)

**Comment by alampros** [comment]
I think this is a typescript configuration issue. In your `tsconfig.json`, make sure it knows how to resolve absolute paths. For example, one of mine looks like this:

```json
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "*": [
        "types/*",
        "*"
      ]
    }
  },

```

Note: If you're not using typescript, make a `jsconfig.json` file instead (vscode uses typescript under the hood to infer types).

**Comment by antoinerousseau** [comment]
Thanks @alampros, this works great!
I added a `jsconfig.json` (since the project is unfortunately not in TS) in the project root, with this:
```json
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "*": ["*"]
    }
  }
}
```

The only details is that I now get suggestions saying
> Could not find a declaration file for module 'config/constants'. '[...]/src/config/constants.js' implicitly has an 'any' type.

But nothing annoying.

**Comment by lsbyerley** [comment]
@antoinerousseau @alampros Do you know how to get rid of those suggestions? I'm using a `jsconfig.json` file as well and i keep seeing those suggestions when using absolute imports.

**Comment by antoinerousseau** [comment]
@lsbyerley you can turn off all VS Code TS suggestions in VS code settings if you want, but I don't know how to fix only these ones.

**Comment by alampros** [comment]
Try disabling the `noImplicitAny` setting. See all the compiler options here: https://www.typescriptlang.org/docs/handbook/compiler-options.html
